rules:
  metadata-required-non-empty:
    field: title
  no-trailing-spaces:
    enabled: true
  no-multiple-blank-lines:
    enabled: true
  require-links:
    enabled: true
overrides:
  - files: ["README.md"]
    rules:
      require-links:
        enabled: false
